
export enum AssetStatus {
  OPERATIONAL = 'Operativo',
  IN_MAINTENANCE = 'En Taller',
  ON_SITE = 'En Obra',
  STAND_BY = 'Stand By',
  OUT_OF_SERVICE = 'Fuera de Servicio',
  RETURNED = 'Devuelto al Proveedor'
}

export enum WorkOrderPriority {
  LOW = 'Baja',
  MEDIUM = 'Media',
  HIGH = 'Alta',
  CRITICAL = 'Crítica'
}

export enum WorkOrderStatus {
  PENDING = 'Pendiente',
  IN_PROGRESS = 'En Proceso',
  COMPLETED = 'Completada',
  CANCELLED = 'Cancelada'
}

export interface AssetExpiration {
  id: string;
  type: 'ITV' | 'Seguro' | 'Cédula Verde' | 'Ruta' | 'Certificación' | 'Habilitación' | 'Otro';
  expirationDate: string; // YYYY-MM-DD
  notes?: string;
}

export interface AssetIncident {
  id: string;
  date: string;
  description: string;
  damageLevel: 'Leve' | 'Moderado' | 'Grave' | 'Destrucción Total';
  cost?: number;
  status: 'Reportado' | 'En Reparación' | 'Cerrado';
  photos?: string[];
  incidentNumber?: string;
  reportUrl?: string;
}

export interface RegulatoryData {
  pat?: { // Puesta a Tierra Res 900/15
    lastDate: string;
    expirationDate: string;
    value: string; // e.g. "3.5 Ohm"
    status: 'Vigente' | 'Vencido' | 'Pendiente';
    certificateUrl?: string;
  };
  lighting?: { // Iluminación Res 84/12
    lastDate: string;
    expirationDate: string;
    avgLux: number;
    status: 'Vigente' | 'Vencido' | 'Pendiente';
  };
  ergonomics?: { // Ergonómico Res 886/15
    lastDate: string;
    expirationDate: string;
    riskLevel: 'Bajo' | 'Medio' | 'Alto';
    status: 'Vigente' | 'Vencido' | 'Pendiente';
  };
}

export type AssetOwnership = 'Propio' | 'Alquilado' | 'Leasing';

export interface AssetDocument {
  id: string;
  assetId: string;
  type: 'Factura' | 'Remito' | 'Título' | 'Tarjeta Verde' | 'Certificación' | 'Contrato' | 'Otro';
  description: string;
  fileUrl?: string;
  createdAt: string;
}

export interface Asset {
  id: string;
  internalId: string; // e.g., ACT-0042
  barcodeId: string; // 4-digit ID (Optional for Rented)
  name: string;
  type: 'Equipos de Informática' | 'Instalaciones en infraestructuras' | 'Maquinaria' | 'Rodados' | 'Mobiliario' | 'Otros';
  description: string; // Keep for backward compatibility or short summary
  status: AssetStatus;
  ownership: AssetOwnership;
  supplier?: string;
  hours: number;
  location: string;
  responsible: string;
  image: string;
  brand: string;
  model: string;
  serial: string;
  year: number; // Manufacturing Year
  dailyRate: number;
  value: number; // Valor Razonable ARS

  // New Fields
  accountingAccount?: string; // Cuenta Contable
  functionalDescription?: string; // Descripción Funcional

  // IT Equipment Specific
  processor?: string;
  ram?: string;
  storage?: string;
  complementaryDescription?: string; // Descripción Complementaria
  originYear?: number; // Año de Origen (Purchase/Acquisition year)
  usefulLifeRemaining?: number; // VÚR (Años)
  tti?: number; // T.T.I. Tasa de Tenencia e Imputación (%)
  domainNumber?: string; // Patente if applicable

  // Identificación Vehicular Adicional
  chassisNumber?: string;
  engineNumber?: string;
  insuranceProvider?: string; // Proveedor de Seguro

  // IT Specific Fields
  operatingSystem?: string;
  ipAddress?: string;
  macAddress?: string;

  expirations?: AssetExpiration[];
  incidents?: AssetIncident[]; // Siniestros
  documents?: AssetDocument[]; // Documentación Adjunta
  averageDailyUsage?: number;
  regulatoryData?: RegulatoryData;
}

export interface WorkOrderUpdate {
  id: string;
  date: string;
  user: string;
  comment: string;
  newStatus?: WorkOrderStatus;
  images?: string[];
}

export interface WorkOrderExpense {
  id: string;
  description: string;
  category: 'Repuesto' | 'Mano de Obra' | 'Consumible' | 'Servicio Externo';
  quantity: number;
  unitCost: number;
  totalCost: number;
  date: string;
}

export interface WorkOrder {
  id: string; // OT-XXXX
  title: string;
  assetId: string;
  assetName: string;
  internalId?: string;
  location?: string;
  status: WorkOrderStatus;
  priority: WorkOrderPriority;
  dateStart: string;
  dateEnd?: string;
  dueDate?: string;
  responsible: string;
  description: string;
  updates: WorkOrderUpdate[];
  expenses: WorkOrderExpense[];
  environmentalNotes?: string;
  environmentalChecklist?: { label: string; checked: boolean }[];
  environmentalFiles?: { name: string; size: string; type: string; date: string }[];

  // Outsourcing Fields
  isOutsourced?: boolean;
  providerId?: string;
  providerName?: string;
  providerInstructions?: string; // Generated by AI for the provider

  // Maintenance Plan Links
  maintenancePlanId?: string;
  maintenanceEventId?: string;
  closingData?: {
    invoiceUrl?: string;
    remitoUrl?: string;
    notes?: string;
    workConfirmation?: boolean;
    closedAt?: string;
    closedBy?: string;
  };
}

export interface ChecklistItem {
  id: string;
  category: string;
  label: string;
  status: 'ok' | 'fail';
  comment: string;
  photoData?: string;
  aiAnalysis?: string;
}

export interface Checklist {
  id: string; // CHK-XXXX
  assetId: string;
  assetName: string;
  date: string;
  inspector: string;
  conformity: number; // 0-100
  items: ChecklistItem[];
}

export interface MaintenanceTask {
  id: string;
  description: string;
  durationDays: number;
  isCritical: boolean;
}

// New Interface for specific events within the plan
export interface MaintenanceEvent {
  id: string;
  title: string; // e.g., "Service 10.000 KM"
  estimatedDate: string; // YYYY-MM-DD
  status: 'Pendiente' | 'Programado' | 'Completado' | 'Vencido';
  triggerValue: number; // The KM or Hour mark (e.g. 10000)
  tasks: MaintenanceTask[]; // Specific tasks for this event
  generatedOtId?: string; // Link to the OT for traceability
}

export interface MaintenancePlan {
  id: string;
  assetId: string;
  assetName: string;
  title: string; // e.g. "Plan Anual 2024"
  baseFrequency?: number; // e.g. every 10000 km
  baseFrequencyUnit?: 'Horas' | 'Kilómetros';
  frequencyTimeValue?: number; // Time based frequency value (e.g. 6)
  frequencyTimeUnit?: 'Días' | 'Semanas' | 'Meses' | 'Años'; // Time based frequency unit
  dailyUsageEstimate: number; // Used to calculate dates
  events: MaintenanceEvent[]; // The scheduled list
  aiAnalysis?: string;
  notes?: string;
  lastExecution?: string; // For compatibility
}

export interface Project {
  id: string;
  internalId: string;
  name: string;
  responsible: string;
  status: 'Activa' | 'Cerrada';
  location: string;
  assignedAssets: number;
  assignedStaff: number;
  comitente?: string;
}

export interface Staff {
  id: string;
  name: string;
  role: string;
  status: string;
  location: string;
  avatar: string;
  assignedAssets: string[];
  email?: string;
  phone?: string;
  dni?: string;
  admissionDate?: string;
  certifications?: string;
  auth?: {
    username: string;
    password: string;
    role: 'SuperAdmin' | 'Admin' | 'User' | 'Viewer';
    permissions: Record<string, 'view' | 'edit'>; // Changed from allowedModules
    canManageUsers: boolean;
  };
}

export interface InventoryItem {
  id: string;
  barcodeId: string; // 4-digit ID
  name: string;
  category: 'Informática' | 'Herramientas' | 'Medición' | 'Muebles y Útiles' | 'Consumibles' | 'Seguridad';
  quantity: number;
  minThreshold: number;
  location: string;
  unitPrice: number;
  type: 'Consumible' | 'Serializado';
  serialNumber?: string;
  status?: 'Disponible' | 'En Reparación' | 'Vencido' | 'Baja';
  expirationDate?: string;
  lastServiceDate?: string;
  assignedTo?: string;
}

export interface ProviderReview {
  id: string;
  provider_id: string;
  user_name: string;
  rating: number;
  comment: string;
  created_at: string;
}

export interface Provider {
  id: string;
  companyName: string;
  contactName: string;
  serviceType: string;
  rating: number; // For backward compatibility/base rating
  status: 'Activo' | 'Inactivo' | 'Potencial';
  phone?: string;
  email?: string;
  averageRating?: number;
  reviewCount?: number;
  reviews?: ProviderReview[];
}

export interface ServiceRequestLogEntry {
  id: string;
  date: string;
  user: string;
  action: string;
  details?: string;
}

export interface ServiceRequestConformity {
  user: string;
  date: string;
  conformity: boolean; // true = Conforme, false = No Conforme
  comment?: string;
}

export interface ServiceRequest {
  id: string;
  title: string;
  category: 'Eléctrico' | 'HVAC' | 'Infraestructura' | 'Conectividad' | 'Herramientas' | 'Seguridad' | 'Otro';
  priority: 'Baja' | 'Media' | 'Alta' | 'Crítica';
  status: 'Pendiente' | 'En Proceso' | 'Resuelto';
  location: string;
  slaDeadline: string;
  description: string;
  relatedInventoryId?: string;
  relatedAssetId?: string; // Nuevo campo para vincular activo
  workOrderId?: string; // ID de la OT generada si aplica
  auditLog: ServiceRequestLogEntry[]; // Bitácora de movimientos
  closureConformity?: ServiceRequestConformity; // Conformidad de cierre
  createdAt?: string; // Fecha de creación exacta
}

export interface Transfer {
  id: string;
  assetName: string;
  fromLocation: string;
  toLocation: string;
  date: string;
  status: 'Pendiente' | 'Programado' | 'En Tránsito' | 'Completado' | 'Cancelado';
  meterReading: number;
  remitoNumber?: string;
  checklist?: ChecklistItem[];
  photos?: string[];
  notes?: string;
  responsibleId?: string;
  conformity?: number;
  aiAnalysis?: string;
}

export interface AssetAllocation {
  id: string;
  assetId: string;
  assetName: string;
  projectId: string;
  projectName: string;
  startDate: string;
  endDate: string;
  status: 'Activo' | 'Programado' | 'Finalizado';
  remitoNumber?: string;
}
